# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore --configuration $(buildConfiguration)
  displayName: 'dotnet restore'

- task: SonarCloudPrepare@1
  displayName: 'Prepare for Sonar Analysis'
  inputs:
    SonarCloud: 'SonarCloud Neruko Project'
    organization: 'lz'
    scannerMode: 'MSBuild'
    projectKey: 'lz.neruko'
    projectName: 'Neruko Project'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Sonar Analyze'

- task: SonarCloudPublish@1
  displayName: 'Publish Sonar analyze results'
  inputs:
    pollingTimeoutSec: '300'